### PR TITLE
 fix FileNotFound Error for local runs with uri_files and AzureMLDataset

### PR DESCRIPTION
**Pull request by Gabriel2409**
Small modifications to the _load function so that uri_file are correctly downloaded for local runs. See issue #68

### CODE REVIEW

**Comment by marrrcin** [comment]
@fdroessler will it fix the problem mentioned in #68 ?

**Comment by fdroessler** [comment]
@marrrcin Yes I was able to reproduce this, not sure why it worked once before for me but in a new setup I can confirm this fixes the issue. @Gabriel2409 can you adjust the comment copied over so it does not refer only to the case in the uri_folder dataset but in general to the case that if the path points to a file we need to take the parent.

**Comment by Gabriel2409** [comment]
@fdroessler, 
I suppose you are talking about these comments:   `# if the filepath is to a file in the folder dataset we need the parent folder` and `# we take the relative within the Azure dataset to avoid downloadingall files in a folder dataset.` I can just remove the word `folder` if needed.

However, even if the solution I proposed works as a workaround, I would like to mention that it leads to download all of the files in the same folder as the uri_file dataset, which may not be what we want as a uri_file dataset is supposed to be only one file.
Indeed, we still loop over the parent: see `for fpath in fs.ls(path_on_azure)` 

Maybe a better solution would be to call `fs.download` directly on `path_on_azure` for uri_file datasets, like this 
```python 
    def _load(self) -> Any:
        if self._download:
            try:
                azureml_ds = self._get_azureml_dataset()
            except ResourceNotFoundError:
                raise VersionNotFoundError(
                    f"Did not find version {self.resolve_load_version()} for {self}"
                )
            fs = AzureMachineLearningFileSystem(azureml_ds.path)
            if azureml_ds.type == "uri_file":
                # relative (to storage account root) path of the file dataset on azure
                path_on_azure = fs._infer_storage_options(azureml_ds.path)[-1]
                logger.info(f"Downloading {path_on_azure} for local execution")
                # using APPEND will keep the local file if exists
                # as versions are unique this will prevent unnecessary file download
                fs.download(path_on_azure, self.download_path, overwrite="APPEND")
            elif azureml_ds.type == "uri_folder":
                # relative (to storage account root) path of the folder dataset on azure
                dataset_root_on_azure = fs._infer_storage_options(azureml_ds.path)[-1]
                # relative (to storage account root) path of the dataset in the folder on azure
                path_on_azure = str(
                    Path(dataset_root_on_azure)
                    / self._dataset_config[self._filepath_arg]
                )
                # if the filepath is to a file in the folder dataset we need the parent folder
                if fs.isfile(path_on_azure):
                    path_on_azure = str(Path(path_on_azure).parent)
                # we take the relative within the Azure dataset to avoid downloading
                # all files in a folder dataset.
                for fpath in fs.ls(path_on_azure):
                    logger.info(f"Downloading {fpath} for local execution")
                    # using APPEND will keep the local file if exists
                    # as versions are unique this will prevent unnecessary file download
                    fs.download(fpath, self.download_path, overwrite="APPEND")
            else:
                raise ValueError("Unsupported AzureMLDataset type")
        return self._construct_dataset().load()

```
This leads to a bit of code duplication but at least you only download the dataset and not other files. And this has the benefit of completely separating uri_file and uri_folder usecases. 

Note that even though this solution seems to work in my case, it leads to failed test cases. I think if this alternate solution is chosen, part of the mock classes and functions will need to be rewritten. 


What do you think?

**Comment by fdroessler** [comment]
You're right, I remember thinking of the case of a file sitting in a folder full of files and that leading to huge download load. So I don't think this is a viable option.

But how about this, we check in both cases (folder/file dataset) if the final path is a file. If yes we download it straight away, no need for `fs.ls()` of determining the parent we already have everything we need. Only in cases of partitioned folder datasets or when we want to download a whole folder we go through individual file download case using `fs.ls()`.

```
            fs = AzureMachineLearningFileSystem(azureml_ds.path)
            if azureml_ds.type == "uri_file":
                # relative (to storage account root) path of the file dataset on azure
                path_on_azure = fs._infer_storage_options(azureml_ds.path)[-1]
            elif azureml_ds.type == "uri_folder":
                # relative (to storage account root) path of the folder dataset on azure
                dataset_root_on_azure = fs._infer_storage_options(azureml_ds.path)[-1]
                # relative (to storage account root) path of the dataset in the folder on azure
                path_on_azure = str(
                    Path(dataset_root_on_azure)
                    / self._dataset_config[self._filepath_arg]
                )
            else:
                raise ValueError("Unsupported AzureMLDataset type")
            # if the filepath is to a file in the folder dataset we need the parent folder
            if fs.isfile(path_on_azure):
                fs.download(path_on_azure, self.download_path, overwrite="APPEND")
            else:
                # we take the relative within the Azure dataset to avoid downloading
                # all files in a folder dataset.
                for fpath in fs.ls(path_on_azure):
                    logger.info(f"Downloading {fpath} for local execution")
                    # using APPEND will keep the local file if exists
                    # as versions are unique this will prevent unnecessary file download
                    fs.download(fpath, self.download_path, overwrite="APPEND")
```

**Comment by Gabriel2409** [comment]
@fdroessler I modified the code following your suggestion. Note that I had to pass the path as a string because the tests were failing if not (even though the actual download when testing it with real azure uri_file datasets in local runs succeeded). 

The reason comes from fsspec:

```python 
def expand_path(self, path, recursive=False, maxdepth=None, **kwargs):
	...
	# No check for Path objects, only strings
    if isinstance(path, str):
        out = self.expand_path([path], recursive, maxdepth)
    else:
        out = set()
        # Leads to PosixPath object is not iterable error during tests
		# which is fortunate because at least the error is not silent
		path = [self._strip_protocol(p) for p in path]  

```

Please note that, as mentionned above, I also removed lines from the `_infer_storage_options` of the `AzureMLFileSystemMock` class. To be honest, I don't know why they were present in the first place as the same operations were performed inside the `_load `function but I may be missing something here. 

Please tell me if you think further modifications are needed.

**Comment by fdroessler** [comment]
lgtm, I think the lines in test were left overs before I got the `fs.is_file` working.

**Comment by marrrcin** [comment]
Looks OK, @Gabriel2409 please update `CHANGELOG.md`.

**Comment by Gabriel2409** [comment]
Hi @marrrcin I updated the changelog. If you are ok with the PR, you can also close the associated issue when merging. 
Thank you :)

**Comment by marrrcin** [comment]
Thanks for your contribution @Gabriel2409

**Pull request merged**
